# Job Tracker - Environment Configuration
# Generated by Terraform

# Database Configuration
DB_NAME=huntr_clone
DB_USER=jobtracker_user
DB_PASSWORD=${db_password}
DB_PORT=5432

# Application Configuration
NODE_ENV=production
APP_PORT=3000
CLIENT_URL=${client_url}
LOG_LEVEL=info

# Authentication Secrets (Auto-generated)
JWT_SECRET=${jwt_secret}
SESSION_SECRET=${session_secret}

# AI Features - Anthropic Claude API
ANTHROPIC_API_KEY=${anthropic_api_key}

# Optional: Google OAuth
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_CALLBACK_URL=${client_url}/api/auth/google/callback

# Optional: AWS S3 Storage
AWS_REGION=
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_S3_BUCKET=

# Optional: Monitoring
CLOUDWATCH_LOG_GROUP=
SENTRY_DSN=
